version: '3'

services:
        db:
                image: postgres
                ports:
                        - "5436:5432"
                environment:
                        - POSTGRES_USER=postgres
                        - POSTGRES_PASSWORD=valea1007
                        - POSTGRES_DB=library
                volumes:
                        - ./dbs/postgres-data:/var/lib/postgresql
        backend:
                container_name: library_backend_container
                build: ./library-server
                command: bash -c "
                        sleep 3 &&
                        python3 manage.py makemigrations && python3 manage.py migrate &&
                        python3 manage.py runserver --insecure 0.0.0.0:8000";
                volumes:
                        - ./library-server:/library-server
                ports:
                        - "8000:8000"
                depends_on:
                        - db
        frontend:
                container_name: library_frontend_container
                build:
                        context: ./library-client
                        dockerfile: Dockerfile
                command: npm start --start;
                volumes:
                        - ./library-client:/library-client
                        - /library-client/node_modules
                ports:
                        - "8080:8080"
                depends_on:
                        - backend