version: '3'
services:
  db:
    image: postgres
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  web:
    build: .
    command: bash -c "sleep 3 && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes: 
      - .:/code
    ports: 
      - "8000:8000"
    links:
      - db
  client:
    container_name: front
    build:
      context: ./vue-blog
      dockerfile: Dockerfile
    command: npm start --start;
    volumes:
      - ./vue-blog:/vue-blog
      - /vue-blog/node_modules
    ports:
      - "8085:8080"
    depends_on:
      - web

