version: '3'

services:
        db:
                image: postgres
                ports:
                        - "5436:5432"
                environment:
                        - POSTGRES_USER=postgres
                        - POSTGRES_PASSWORD=290996
                        - POSTGRES_DB=college
                volumes:
                        - ./dbs/postgres-data:/var/lib/postgresql
        backend:
                container_name: college_backend_container
                build: ./college-backend
                command: bash -c "
                        sleep 3 &&
                        python3 manage.py makemigrations && python3 manage.py migrate &&
                        python3 manage.py runserver --insecure 0.0.0.0:8000";
                volumes:
                        - ./college-backend:/college-backend
                ports:
                        - "8000:8000"
                depends_on:
                        - db
        frontend:
                container_name: college_frontend_container
                build:
                        context: ./college-frontend
                        dockerfile: Dockerfile
                command: npm start --start;
                volumes:
                        - ./college-frontend:/college-frontend
                        - /college-frontend/node_modules
                ports:
                        - "8080:8080"
                depends_on:
                        - backend