version: '3'

services:
        django_hotel_db:
                image: postgres
                ports:
                        - "5436:5432"
                environment:
                        - POSTGRES_USER=postgres
                        - POSTGRES_PASSWORD=postgres
                        - POSTGRES_DB=django_hotel_db
                volumes:
                        - ./dbs/postgres-data:/var/lib/postgresql
        backend:
                container_name: django_hotel_backend
                build: ./django_hotel
                command: bash -c "
                        sleep 5 &&
                        python3 manage.py makemigrations && python3 manage.py migrate &&
                        python3 manage.py runserver --insecure 0.0.0.0:8000";
                volumes:
                        - ./django_hotel:/django_hotel
                ports:
                        - "8000:8000"
                depends_on:
                        - django_hotel_db
        frontend:
                container_name: django_hotel_frontend
                build:
                        context: ./vue_hotel
                        dockerfile: Dockerfile
                command: npm start --start;
                volumes:
                        - ./vue_hotel:/vue_hotel
                        - /vue_hotel/node_modules
                ports:
                        - "8080:8080"
                depends_on:
                        - backend

